const { JSDOM } = require('jsdom'); const fs = require('fs');
const dom = new JSDOM(fs.readFileSync(process.argv[2], 'utf8'), { runScripts: 'dangerously' });
const d = dom.window.document; const errs = []; dom.window.addEventListener('error', e => errs.push(e.message));
const on = sel => [...d.querySelectorAll(sel)].findIndex(e => e.classList.contains('on'));
console.log('head tabs', d.querySelectorAll('.hb').length, '| jets', d.querySelectorAll('.jb').length, '| active head panel', on('.head'));
d.querySelectorAll('.hb')[5].click(); console.log('after clicking head tab 6: active panel', on('.head'), '| jet table rows', d.querySelectorAll('#jet tr').length, '| jetbox inside panel 6:', d.querySelectorAll('.head')[5].contains(d.getElementById('jetbox')));
d.querySelectorAll('.jb')[17].click(); console.log('after clicking jet 18: header', d.querySelector('#jet .cnt').textContent.slice(0, 90));
d.querySelectorAll('#h5 .nbtn')[3].click(); console.log('after clicking neuron 4 of head 6: visible neuron', [...d.querySelectorAll('#h5 .neu')].findIndex(e => e.classList.contains('on')));
d.querySelectorAll('#jet tr.p')[0].click(); console.log('particle click (needs score formulas; S5 keeps ParT weights):', d.getElementById('contrib').textContent.slice(0, 80));
console.log('errors:', errs.length ? errs : 'none');
